# Generated by Django 3.0.6 on 2020-05-23 07:50

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('stage', models.CharField(choices=[('AP', 'Applied'), ('PS', 'Phone Screen'), ('OS', 'On site'), ('OF', 'Offered'), ('AC', 'Accepted'), ('RE', 'Rejected')], max_length=2)),
                ('resume', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/media/uploads'), upload_to='')),
            ],
        ),
    ]
