# Generated by Django 2.2 on 2020-05-26 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='comments',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='candidate',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
