# Generated by Django 2.2 on 2020-05-26 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200526_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.SmallIntegerField()),
                ('Candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.Candidate')),
            ],
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
