# Generated by Django 2.2.12 on 2020-05-26 07:05

import backend.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200526_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.FileField(blank=True, null=True, storage=backend.storages.PublicMediaStorage(), upload_to=''),
        ),
    ]
